company=input("¿Nombre de la compañia?: ")
mozo=int(input("¿Cuantos mozos?: "))
web=("webURL")
dominio=(".com")
admin=("admin@"+company+dominio)
contador=("contador@"+company+dominio)
ventas=("caja@"+company+dominio)
password=("passwd")
PIN1=("1111")
PIN2=("2222")
PIN3=("3333")
PIN4=("4444")
PIN5=("5555")
PIN6=("6666")
mozo1=("mozo1@"+company+dominio)
mozo2=("mozo2@"+company+dominio)
mozo3=("mozo3@"+company+dominio)
mozo4=("mozo4@"+company+dominio)
mozo5=("mozo5@"+company+dominio)
mozo6=("mozo5@"+company+dominio)
print(""
 "")
print("CREDENCIALES: ")
print(" ")
print("WEB: "+web)
print(" ")
print("ADMINISTRADOR = "+admin)
print("CONTADOR = "+contador)
print("CAJA = "+ventas)
if mozo == 1:
    print("MOZO = " + mozo1,"     PIN "+PIN1)
if mozo == 2:
    print("MOZO1 = "+ mozo1,"    PIN "+PIN1)
    print("MOZO2 = "+ mozo2,"    PIN "+PIN2)
if mozo ==3:
    print("MOZO1 = "+ mozo1,"    PIN "+PIN1)
    print("MOZO2 = "+ mozo2,"    PIN "+PIN2)
    print("MOZO3 = "+ mozo3,"    PIN "+PIN3)
if mozo ==4:
    print("MOZO1 = "+ mozo1,"    PIN "+PIN1)
    print("MOZO2 = "+ mozo2,"    PIN "+PIN2)
    print("MOZO3 = "+ mozo3,"    PIN "+PIN3)
    print("MOZO4 = "+ mozo4,"    PIN "+PIN4)
if mozo ==5:
    print("MOZO1 = "+ mozo1,"    PIN "+PIN1)
    print("MOZO2 = "+ mozo2,"    PIN "+PIN2)
    print("MOZO3 = "+ mozo3,"    PIN "+PIN3)
    print("MOZO4 = "+ mozo4,"    PIN "+PIN4)
    print("MOZO5 = "+ mozo5,"    PIN "+PIN5)
if mozo ==6:
    print("MOZO1 = "+ mozo1,"    PIN "+PIN1)
    print("MOZO2 = "+ mozo2,"    PIN "+PIN2)
    print("MOZO3 = "+ mozo3,"    PIN "+PIN3)
    print("MOZO4 = "+ mozo4,"    PIN "+PIN4)
    print("MOZO5 = "+ mozo5,"    PIN "+PIN5)
    print("MOZO6 = "+ mozo6,"    PIN "+PIN6)        
else:
    False
print(" ")
print("CONTRASEÑA TODOS LOS USUARIOS: ", password)
